services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: ${PROJECT_NAME}-postgres

  web:
    build: .
    command: sh -c "python3 manage.py migrate &&
      yes | python3 manage.py collectstatic --no-input &&
      gunicorn teki_game.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  redis:
    image: redis:7.0.2-alpine
    container_name: ${PROJECT_NAME}-redis
    restart: unless-stopped
    volumes:
      - redis:/data
    env_file:
      - ./.env

volumes:
  postgres_data:
  redis:
    driver: local
