# Generated by Django 5.1 on 2024-08-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='config',
            field=models.ManyToManyField(blank=True, to='common.commonconfigurationjsonconfig', verbose_name='Config'),
        ),
    ]
